### ISSUE TITLE
[API] 모임 생성시 시작-종료-모집마감 날짜 입력 조건 추가

### ISSUE THREAD

**Issue by krimson701** [DaeDo-Crew/SSHJ#11]
모임 생성시 
1. 시작 날짜 보다 끝나는 날짜가 빠르면안되고
2. 끝나는 날짜가 모집 마감날짜보다 빨라도 되는지 토의

이러한 점들을 프론트 단에서 할지 백단에서 할지 얘기해봐야합니다

**Comment by hoyeon94** [comment]
제가 하는게 맞는 것 같습니다~ 나중에 정리하면서 하겠수다~ 감사여

**Comment by koreanhole** [comment]
시작날짜 <= 종료날짜
끝나는날짜 <= 모집 마감날짜
이렇게 되야하지 않을까유
모임이 끝나는 날까지도 모집을 받을 수 있으니..?

**Comment by hoyeon94** [comment]
찬성합니당22
