### ISSUE TITLE
[API] 모임 생성 API 500뜹니다

### ISSUE THREAD

**Issue by hoyeon94** [DaeDo-Crew/SSHJ#12]
## 수정이 필요한 parameter
- 없습니당

## 수정이 필요한 이유
<p>
@RequestMapping(value = "/create", method= RequestMethod.POST)
    public ResponseEntity<Void> createMeeting(
            @ApiIgnore @RequestAttribute("UserHeaderInfo") UserHeaderModel userHeaderModel,
            @ModelAttribute MeetingDto meetingDto) throws Exception{
        meetingService.insertMeeting(meetingDto);
        // 모임 생성 시 해당 동아리를 구독 중이던 유저들에게 푸시알림
>>>>>>>>>>>>>>>이게 문제인듯        expoPushService.sendingPushMeetingCreated(userHeaderModel.getUserId());
        return new ResponseEntity<Void>(HttpStatus.OK);
    }
확인부탁드립니다
</p>
-모임 추가는 되는데, 500에러가 리턴되서 meeting ID를 받을 수가 없어욤

**Comment by do168** [comment]
expo push 임시 주석 처리했습니다. 현재 타 디바이스 APP에서 로그인 시 Expo Push Token이 넘어오지 않아 NULL로 토큰이 넘겨져서 생기는 오류같습니다.

**Comment by hoyeon94** [comment]
확인감사요!수정확인했습니다
