### ISSUE TITLE
[API]meeting/create

### ISSUE THREAD

**Issue by hoyeon94** [DaeDo-Crew/SSHJ#13]
## 수정이 필요한 parameter
- 없음

## 수정이 필요한 response
- 추가
  - meeting_id가 필요합니다.

- 삭제
  - meeting_place: 모임 장소

## 수정이 필요한 http method
없음

## 수정이 필요한 이유
- 모임이 생성된 후 meeting ID를 받아야 하는데 data가 비어있습니다! 확인보탁욤

**Comment by do168** [comment]
merge 과정에서 충돌이 있었던 것 같습니다. 해결했습니다
