### ISSUE TITLE
[API] 비밀번호 재설정 api 작동 오류

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#17]
## 수정이 필요한 response
# 수정이 필요한 http method

## 수정이 필요한 이유
- PATCH request를 보낼경우 존재하지 않는 아이디라며 500에러를 되돌려줍니다.(로그인도 정상적으로 가능한 아이디)

**Comment by do168** [comment]
저녁에 고쳐보겠슴다
