### ISSUE TITLE
[API] 유저별 참여 모임 읽는 api 수정

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#19]
## 수정이 필요한 api
- /meeting/user/list

## 수정이 필요한 parameter
- userid

## 수정이 필요한 http method
없음

## 수정이 필요한 이유
- userId가 존재하지 않습니다.

**Comment by krimson701** [comment]
테스트해보시고 말씀주세영

**Comment by koreanhole** [comment]
잘됩니당
