### ISSUE TITLE
[API] 동아리 통합 api응답에 구독자 수 정보 추가 요청

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#20]
## 수정이 필요한 api
- /club/ClubPackage

## 수정이 필요한 parameter
- 없음

## 수정이 필요한 response
- 추가
  - numSubscribe: 구독자 수

## 수정이 필요한 http method
없음

## 수정이 필요한 이유
- 구독자 수도 받을 수 있다면 좋겠습니다.

**Comment by do168** [comment]
추가 완료 하였습니다
