### ISSUE TITLE
[API] 심심했지에 등록된 전체 동아리의 이름과 clubId를 알 수 있는 API요청

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#21]
## 예상되는 parameter
- 없음

## 필요한 response
- club_name
- club_id

ex)
```
[
{
   club_name: @#$,
   club_id: 1234243,
},
{
   club_name: askdjaskldj,
   club_id: 123238,
},
]
```
## 필요한 http method
GET

## 필요한 이유
- 홈화면 및 동아리 상세페이지에서 해당 데이터를 사용자에게 보여주기 위해

**Comment by do168** [comment]
혹시 club_id String 형식으로 리턴해도 괜찮습니까

**Comment by koreanhole** [comment]
> 혹시 club_id String 형식으로 리턴해도 괜찮습니까

원래 club_id가 string으로 오나여?
string이어도 상관은 없습네다

**Comment by do168** [comment]
원래 long 타입으로 보낼라 했는데 스웨거에서 오류 비스무리 하게 나서 그랬습니다. 일단 배포하겠습니다. 그리고 이 API를 일단 ClubController로 두긴 했는데 혹시 로그인 안하고도 볼 수 있게 만들거면 옮기겠습니다

**Comment by koreanhole** [comment]
아 아닙니당 로그인 하고 봐야할것 같네여

**Comment by koreanhole** [comment]
푸시 올라왔으니 이슈 닫겠습니다
