### ISSUE TITLE
[API] 회원탈퇴 기능

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#22]
## 예상되는 parameter
- email?
- accessToken(header)?

## 필요한 http method
DELETE

## 필요한 이유
- 회원가입 기능 테스트 위해 탈퇴 -> 재가입 반복 하려고 합니다.
- 찾아보니 인터넷 진흥원에서 [이와 같이 개인정보를 수집하는 웹사이트들은 이용자들의 개인정보보호를 위해 회원탈퇴. 에 대한 이용자 권리를 보장하고 회원탈퇴를 위한 방안을 마련할 필요가 있다.]라고 하네여

**Comment by do168** [comment]
최대한 빠른 시일 내에 완료하겠습니다.

**Comment by do168** [comment]
파라미터는 토큰만 있으면 가능할 거 같습니다
