### ISSUE TITLE
[API] /meeting/club/list 현재 인원 표시 문제

### ISSUE THREAD

**Issue by hoyeon94** [DaeDo-Crew/SSHJ#25]
## 수정이 필요한 api
-/meeting/club/list 

## 수정이 필요한 이유
-해당 api로 모든 모임 목록을 불러오면, curparticipant가 무조건 0이네요
확인보탁드립니다~

**Comment by krimson701** [comment]
이거 해결됐습니까?

**Comment by do168** [comment]
해결완료
