### ISSUE TITLE
[API] 모임에 참여한 인원을 확인하는 API

### ISSUE THREAD

**Issue by hoyeon94** [DaeDo-Crew/SSHJ#26]
## 예상되는 parameter
- meeting_id

## 필요한 response
- 모임참여자 user_id나 nickname이나 기타등등정보들

## 필요한 http method
GET

## 필요한 이유
- 모임관리 할 때 필요할 듯 싶습니다,,
- 혹시 있는데 제가 못 찾는거면 말해주십쇼

**Comment by do168** [comment]
혹시 누가 쓰는 api인가요?

**Comment by krimson701** [comment]
확인해주시고 이슈 닫아주세용

**Comment by hoyeon94** [comment]
확인했수다
