### ISSUE TITLE
[API] 동아리별 모임 읽기api에서 동아리 이름이 null로 표시되는 문제

### ISSUE THREAD

**Issue by koreanhole** [DaeDo-Crew/SSHJ#28]
## 수정이 필요한 api
- /member/club/list

## 수정이 필요한 parameter
- 없음

## 수정이 필요한 response
- clubName

## 수정이 필요한 http method
없음

## 수정이 필요한 이유
- clubName이 적절한 동아리 이름으로 표시되는것이 아닌 null로 표시됩니다.

**Comment by do168** [comment]
해결 완료했습니다.
