### ISSUE TITLE
[API]/club/countNoticeLike 동아리 공지 좋아요 갯수 Api

### ISSUE THREAD

**Issue by hoyeon94** [DaeDo-Crew/SSHJ#30]
## 수정이 필요한 api
- /club/countNoticeLike
동아리 공지 좋아요 갯수 Api

## 수정이 필요한 이유
-swagger에서 500에러가 뜹니다 확인 부탁드려용~

**Comment by hoyeon94** [comment]
notice like도 안되느넫 지금 그냥 안쓰는 api인가염?

**Comment by koreanhole** [comment]
넴 아직은 안넣었어여

**Comment by koreanhole** [comment]
모임 좋아요랑 공지 좋아요 아직 안넣었슴다

**Comment by krimson701** [comment]
앗 감사합니ㅔ이

**Comment by do168** [comment]
해결했습니다
